## House Price Prediction Using Linear Regression

In [38]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt
from sklearn import linear_model
%matplotlib inline

In [2]:
df = pd.read_csv("F:/ML Predictor/homeprices.csv")
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [4]:
df = df.drop(["bedrooms", "age"], axis=1)
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  595000
4  4000  760000

In [34]:
model = linear_model.LinearRegression()
model.fit(df[['area']].values, df[['price']].values)

LinearRegression()

In [35]:
model.coef_

array([[167.30954677]])

In [36]:
model.intercept_

array([76692.38187078])

In [37]:
model.predict([[5000]])

array([[913240.11571842]])

In [40]:
import pickle

In [41]:
with open('model_pickle', 'wb') as f:
    pickle.dump(model, f)

In [42]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [44]:
mp.predict([[5000]])

array([[913240.11571842]])

In [ ]:
# the house with the area = 5000 sqft
# price of that house will be = $ 913240.12 